# https://www.appveyor.com/docs/appveyor-yml

install:
  # Install DocBook XSL.
  - ps: Start-FileDownload 'https://github.com/docbook/xslt10-stylesheets/releases/download/release%2F1.79.2/docbook-xsl-nons-1.79.2.zip'
  - 7z x docbook-xsl-nons-1.79.2.zip -oC:\
  # Install Pygments.
  - pip install pygments
  # Install xsltproc.
  - choco install xsltproc
  # Git on AppVeyor includes a non-functional xsltproc. Remove this.
  - if exist "%ProgramFiles%\Git\usr\bin\xsltproc.exe" del "%ProgramFiles%\Git\usr\bin\xsltproc.exe"

build_script:
  - set XSL_BASE_PATH=C:/docbook-xsl-nons-1.79.2
  # Other make executables are in C:\cygwin64\bin and C:\msys64\usr\bin.
  - C:\cygwin\bin\make html-dist

test: off
